# Generated by Django 2.2.6 on 2020-05-16 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date1', models.DateField(null=True)),
                ('bike', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bike.Bike_detail')),
                ('signup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bike.Signup')),
            ],
        ),
    ]
