# Generated by Django 2.2.6 on 2020-05-16 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0002_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Send_Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('message1', models.TimeField(null=True)),
                ('signup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bike.Signup')),
            ],
        ),
    ]
