from django.contrib import admin
from django.urls import path
from bike.views import *
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Home,name="home"),
    path('admin_home', Admin_Home, name="admin_home"),
    path('login_user', Login, name="login_user"),
    path('login_admin', Admin_Login, name="login_admin"),
    path('logout', Logout, name="logout"),
    path('about', About, name="about"),
    path('signup', signup_user, name="signup"),
    path('contact', Contact, name="contact"),
    path('view_bike_type', View_bike_type, name="view_bike_type"),
    path('view_bike_detail/(<int:pid>)', View_Bike_Detail, name="view_bike_detail"),
    path('view_bike_type/(<int:pid>)', view_bike_type, name="view_bike_type"),
    path('view_bike_index/(<int:pid>)', view_bike_index, name="view_bike_index"),
    path('view_feel_zoom/(<int:pid>)', View_Zoom_Feel, name="view_feel_zoom"),
    path('send_feedback/(<int:pid>)', Feedback, name="send_feedback"),
    path('view_order/(<str:error>)', View_Order, name="view_order"),
    path('view_bike_price/(<str:price>)', view_bike_price, name="view_bike_price"),
    path('add_bike_type', Add_bike_type, name="add_bike_type"),
    path('add_bike', Add_Bike, name="add_bike"),
    path('add_company', Add_company, name="add_company"),
    path('view_bike', View_Bike, name="view_bike"),
    path('profile', profile, name="profile"),
    path('view_feedback', view_feedback, name="view_feedback"),
    path('view_company', View_Company, name="view_company"),
    path('view_customer', view_customer, name="view_customer"),
    path('view_booking', View_Booking, name="view_booking"),
    path('view_new_booking', View_New_Booking, name="view_new_booking"),
    path('view_company_customer', View_Company_Customer, name="view_company_customer"),
    path('view_bike_customer/(<int:pid>)', View_Bike_Customer, name="view_bike_customer"),
    path('view_booking_detail/(<int:pid>)', View_Booking_Detail, name="view_booking_detail"),
    path('assign_status/(<int:pid>)', Edit_status, name="assign_status"),
    path('edit_bike/(<int:pid>)', Edit_Bike, name="edit_bike"),
    path('edit_company/(<int:pid>)', Edit_company, name="edit_company"),
    path('edit_bike_type/(<int:pid>)', Edit_bike_type, name="edit_bike_type"),
    path('delete_bike_type/(<int:pid>)', delete_bike_type, name="delete_bike_type"),
    path('delete_bike/(<int:pid>)', delete_bike, name="delete_bike"),
    path('delete_company/(<int:pid>)', delete_company, name="delete_company"),
    path('delete_feedback/(<int:pid>)', delete_feedback, name="delete_feedback"),
    path('delete_user/(<int:pid>)', delete_user, name="delete_user"),
    path('delete_booking/(<int:pid>)', delete_booking, name="delete_booking"),
    path('booking/(<int:pid>)', Booking_Order, name="booking"),
    path('edit_profile', Edit_profile, name="edit_profile"),
]+static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)
